In [9]:
#selenium 설치
!pip install selenium

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import pandas as pd

#옵션 설정
options=Options()
options.add_argument('==kiosk')
options.add_argument('--start-fullscreen')

Requirement already satisfied: selenium in c:\conda\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\conda\lib\site-packages (from selenium) (1.25.8)

In [2]:
#크롬 드라이버 불러오기
driver = webdriver.Chrome("chromedriver.exe")

In [10]:
team_list=["NC","두산","KT","LG","키움","KIA","롯데","삼성","SK","한화","넥센"]

In [11]:
data=pd.DataFrame()

In [12]:
#스탯티즈 선수별 타격 기록 url 분할
url_1="http://www.statiz.co.kr/stat.php?opt=0&sopt=0&re=0&ys="
url_2="&ye="
url_3="&se=0&te="
url_4="&tm=&ty=0&qu=auto&po=0&as=&ae=&hi=&un=&pl=&da=1&o1=WAR_ALL_ADJ&o2=TPA&de=1&lr=0&tr=&cv=&ml=1&sn=30&si=&cn="

In [15]:
# 각 팀마다 2001~2020년 타격데이터 수집
for team in team_list:
    for year in range(2001,2021):
        # url 접속
        driver.get(url_1+str(year)+url_2+str(year)+url_3+team+url_4)
        
        # 데이터 저장을 위한 빈 리스트 생성
        list_name=[]
        list_game=[]
        list_WAR=[]
        list_PA=[]
        list_AB=[]
        list_R=[]
        list_H=[]
        list_B2=[]
        list_B3=[]
        list_HR=[]
        list_TB=[]
        list_RBI=[]
        list_SB=[]
        list_CS=[]
        list_BB=[]
        list_HBP=[]
        list_IBB=[]
        list_K=[]
        list_GIDP=[]
        list_SF=[]
        list_SH=[]
        list_AVG=[]
        list_OBP=[]
        list_SLG=[]
        list_OPS=[]
        list_wOBA=[]
        list_wRC=[]
        list_WPA=[]
        
        #xpath를 통해 데이터 수집
        try:
            for i in range(3,37):
                if i==13 or i==14 or i==25 or i==26:
                    continue
                name=driver.find_element_by_xpath('//*[@id="fixcol"]/table/tbody/tr['+str(i)+']/td[2]/a')
                WAR=driver.find_element_by_xpath('//*[@id="fixcol"]/table/tbody/tr['+str(i)+']/td[4]/font/span')
                game=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[5]/font/span')
                PA=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[6]/a/font/span')
                AB=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[7]/a/font/span')
                R=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[8]/font/span')
                H=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[9]/a/font/span')
                B2=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[10]/a/font/span')
                B3=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[11]/a/font/span')
                HR=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[12]/a/font/span')
                TB=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[13]/font/span')
                RBI=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[14]/a/font/span')
                SB=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[15]/a/font/span')
                CS=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[16]/a/font/span')
                BB=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[17]/a/font/span')
                HBP=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[18]/a/font/span')
                IBB=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[19]/a/font/span')
                K=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[20]/font/span')
                GIDP=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[21]/a/font/span')
                SH=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[22]/a/font/span')
                SF=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[23]/a/font/span')
                AVG=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[24]/a/font/span')
                OBP=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[25]/a/font/span')
                SLG=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[26]/a/font/span')
                OPS=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[27]/a/font/span')
                wOBA=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[28]/font/span')
                wRC=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr['+str(i)+']/td[29]/font/span')
                WPA=driver.find_element_by_xpath('//*[@id="mytable"]/tbody/tr[3]/td[31]/font/span')
                list_name.append(name.text)
                list_game.append(game.text)
                list_WAR.append(WAR.text)
                list_PA.append(PA.text)
                list_AB.append(AB.text)
                list_R.append(R.text)
                list_H.append(H.text)
                list_B2.append(B2.text)
                list_B3.append(B3.text)
                list_HR.append(HR.text)
                list_TB.append(TB.text)
                list_RBI.append(RBI.text)
                list_SB.append(SB.text)
                list_CS.append(CS.text)
                list_BB.append(BB.text)
                list_HBP.append(HBP.text)
                list_IBB.append(IBB.text)
                list_K.append(K.text)
                list_GIDP.append(GIDP.text)
                list_SF.append(SF.text)
                list_SH.append(SH.text)
                list_AVG.append(AVG.text)
                list_OBP.append(OBP.text)
                list_SLG.append(SLG.text)
                list_OPS.append(OPS.text)
                list_wOBA.append(wOBA.text)
                list_wRC.append(wRC.text)
                list_WPA.append(WPA.text)
                
        #데이터가 없는경우 다음 루프 진행
        except:
            continue
        
        #리스트를 데이터프레임으로 변환 후 저장
        player_data=pd.DataFrame({'이름':list_name,'경기':list_game,
                                '타석':list_PA,'타수':list_AB,
                                '득점':list_R,'안타':list_H,
                                 '2타':list_B2,'3타':list_B3,
                                '홈런':list_HR,'루타':list_TB,
                                '타점':list_RBI,'도루':list_SB,
                                '도실':list_CS,'볼넷':list_BB,
                                '사구':list_HBP,'고4':list_IBB,
                                '삼진':list_K,'병살':list_GIDP,
                                '희타':list_SH,'희비':list_SF
                                ,'타율':list_AVG,'출루':list_OBP,
                                '장타':list_SLG,'OPS':list_OPS,
                                'wOBA':list_wOBA,'wRC+':list_wRC,
                                'WPA':list_WPA})
        data=data.append(player_data)

In [16]:
#저장된 데이터프레임
data

,이름,경기,타석,타수,득점,안타,2타,3타,홈런,루타,...,병살,희타,희비,타율,출루,장타,OPS,wOBA,wRC+,WPA
0,테임즈,125,514,443,95,152,30,6,37,305,...,6,0,6,.343,.422,.688,1.111,.464,168.3,6.63
1,나성범,123,536,477,88,157,28,5,30,285,...,4,1,1,.329,.400,.597,.998,.429,146.2,6.63
2,박민우,118,491,416,87,124,21,9,1,166,...,5,4,4,.298,.392,.399,.791,.367,106.9,6.63
3,손시헌,97,361,307,39,90,20,1,5,127,...,10,5,8,.293,.368,.414,.782,.352,96.1,6.63
4,이종욱,124,495,438,73,126,28,4,6,180,...,5,1,13,.288,.342,.411,.753,.339,87.8,6.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,유재신,16,15,15,0,3,0,0,0,3,...,0,0,0,.200,.200,.200,.400,.185,-9.2,3.21
26,김웅빈,67,142,135,18,34,8,0,3,51,...,3,0,0,.252,.289,.378,.667,.297,66.1,3.21
27,박정음,81,162,140,26,34,4,1,2,46,...,0,4,1,.243,.323,.329,.651,.296,64.8,3.21
28,김지수,64,40,35,7,6,0,0,1,9,...,0,1,2,.171,.205,.257,.462,.200,2.5,3.21
29,김재현,70,88,84,6,14,2,0,2,22,...,4,0,0,.167,.205,.262,.467,.211,9.0,3.21

In [19]:
#csv파일로 변환
data.to_csv("baseball_hitter_data.csv",encoding="euc-kr",index=None)